spring:
  application:
    name: msuser
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  web:
    locale-resolver: fixed
    locale: pt_BR
  mvc:
    format:
      date-time: iso
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
mq:
  queues:
    ms-notification: ms-notification
springdoc:
  swagger-ui:
    path: /index.html
  api-docs:
    path: /ms-user
  packages-to-scan: com.raphael.msuser.web.controller